# Generated by Django 2.0.6 on 2018-06-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='limit',
            new_name='attendees_limit',
        ),
    ]
